// Code generated by ent, DO NOT EDIT.

package channelhealthproberun

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldEQ(FieldUpdatedAt, v))
}

// ChannelID applies equality check predicate on the "channel_id" field. It's identical to ChannelIDEQ.
func ChannelID(v int) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldEQ(FieldChannelID, v))
}

// ModelID applies equality check predicate on the "model_id" field. It's identical to ModelIDEQ.
func ModelID(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldEQ(FieldModelID, v))
}

// Stream applies equality check predicate on the "stream" field. It's identical to StreamEQ.
func Stream(v bool) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldEQ(FieldStream, v))
}

// TtfbMs applies equality check predicate on the "ttfb_ms" field. It's identical to TtfbMsEQ.
func TtfbMs(v float64) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldEQ(FieldTtfbMs, v))
}

// TtftMs applies equality check predicate on the "ttft_ms" field. It's identical to TtftMsEQ.
func TtftMs(v float64) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldEQ(FieldTtftMs, v))
}

// TotalMs applies equality check predicate on the "total_ms" field. It's identical to TotalMsEQ.
func TotalMs(v float64) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldEQ(FieldTotalMs, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldEQ(FieldErrorMessage, v))
}

// ScheduleKey applies equality check predicate on the "schedule_key" field. It's identical to ScheduleKeyEQ.
func ScheduleKey(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldEQ(FieldScheduleKey, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldEQ(FieldStartedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldEQ(FieldCompletedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldLTE(FieldUpdatedAt, v))
}

// ChannelIDEQ applies the EQ predicate on the "channel_id" field.
func ChannelIDEQ(v int) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldEQ(FieldChannelID, v))
}

// ChannelIDNEQ applies the NEQ predicate on the "channel_id" field.
func ChannelIDNEQ(v int) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNEQ(FieldChannelID, v))
}

// ChannelIDIn applies the In predicate on the "channel_id" field.
func ChannelIDIn(vs ...int) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldIn(FieldChannelID, vs...))
}

// ChannelIDNotIn applies the NotIn predicate on the "channel_id" field.
func ChannelIDNotIn(vs ...int) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNotIn(FieldChannelID, vs...))
}

// ModelIDEQ applies the EQ predicate on the "model_id" field.
func ModelIDEQ(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldEQ(FieldModelID, v))
}

// ModelIDNEQ applies the NEQ predicate on the "model_id" field.
func ModelIDNEQ(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNEQ(FieldModelID, v))
}

// ModelIDIn applies the In predicate on the "model_id" field.
func ModelIDIn(vs ...string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldIn(FieldModelID, vs...))
}

// ModelIDNotIn applies the NotIn predicate on the "model_id" field.
func ModelIDNotIn(vs ...string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNotIn(FieldModelID, vs...))
}

// ModelIDGT applies the GT predicate on the "model_id" field.
func ModelIDGT(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldGT(FieldModelID, v))
}

// ModelIDGTE applies the GTE predicate on the "model_id" field.
func ModelIDGTE(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldGTE(FieldModelID, v))
}

// ModelIDLT applies the LT predicate on the "model_id" field.
func ModelIDLT(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldLT(FieldModelID, v))
}

// ModelIDLTE applies the LTE predicate on the "model_id" field.
func ModelIDLTE(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldLTE(FieldModelID, v))
}

// ModelIDContains applies the Contains predicate on the "model_id" field.
func ModelIDContains(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldContains(FieldModelID, v))
}

// ModelIDHasPrefix applies the HasPrefix predicate on the "model_id" field.
func ModelIDHasPrefix(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldHasPrefix(FieldModelID, v))
}

// ModelIDHasSuffix applies the HasSuffix predicate on the "model_id" field.
func ModelIDHasSuffix(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldHasSuffix(FieldModelID, v))
}

// ModelIDEqualFold applies the EqualFold predicate on the "model_id" field.
func ModelIDEqualFold(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldEqualFold(FieldModelID, v))
}

// ModelIDContainsFold applies the ContainsFold predicate on the "model_id" field.
func ModelIDContainsFold(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldContainsFold(FieldModelID, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v Source) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v Source) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...Source) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...Source) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNotIn(FieldSource, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNotIn(FieldStatus, vs...))
}

// StreamEQ applies the EQ predicate on the "stream" field.
func StreamEQ(v bool) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldEQ(FieldStream, v))
}

// StreamNEQ applies the NEQ predicate on the "stream" field.
func StreamNEQ(v bool) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNEQ(FieldStream, v))
}

// TtfbMsEQ applies the EQ predicate on the "ttfb_ms" field.
func TtfbMsEQ(v float64) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldEQ(FieldTtfbMs, v))
}

// TtfbMsNEQ applies the NEQ predicate on the "ttfb_ms" field.
func TtfbMsNEQ(v float64) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNEQ(FieldTtfbMs, v))
}

// TtfbMsIn applies the In predicate on the "ttfb_ms" field.
func TtfbMsIn(vs ...float64) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldIn(FieldTtfbMs, vs...))
}

// TtfbMsNotIn applies the NotIn predicate on the "ttfb_ms" field.
func TtfbMsNotIn(vs ...float64) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNotIn(FieldTtfbMs, vs...))
}

// TtfbMsGT applies the GT predicate on the "ttfb_ms" field.
func TtfbMsGT(v float64) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldGT(FieldTtfbMs, v))
}

// TtfbMsGTE applies the GTE predicate on the "ttfb_ms" field.
func TtfbMsGTE(v float64) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldGTE(FieldTtfbMs, v))
}

// TtfbMsLT applies the LT predicate on the "ttfb_ms" field.
func TtfbMsLT(v float64) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldLT(FieldTtfbMs, v))
}

// TtfbMsLTE applies the LTE predicate on the "ttfb_ms" field.
func TtfbMsLTE(v float64) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldLTE(FieldTtfbMs, v))
}

// TtfbMsIsNil applies the IsNil predicate on the "ttfb_ms" field.
func TtfbMsIsNil() predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldIsNull(FieldTtfbMs))
}

// TtfbMsNotNil applies the NotNil predicate on the "ttfb_ms" field.
func TtfbMsNotNil() predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNotNull(FieldTtfbMs))
}

// TtftMsEQ applies the EQ predicate on the "ttft_ms" field.
func TtftMsEQ(v float64) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldEQ(FieldTtftMs, v))
}

// TtftMsNEQ applies the NEQ predicate on the "ttft_ms" field.
func TtftMsNEQ(v float64) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNEQ(FieldTtftMs, v))
}

// TtftMsIn applies the In predicate on the "ttft_ms" field.
func TtftMsIn(vs ...float64) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldIn(FieldTtftMs, vs...))
}

// TtftMsNotIn applies the NotIn predicate on the "ttft_ms" field.
func TtftMsNotIn(vs ...float64) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNotIn(FieldTtftMs, vs...))
}

// TtftMsGT applies the GT predicate on the "ttft_ms" field.
func TtftMsGT(v float64) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldGT(FieldTtftMs, v))
}

// TtftMsGTE applies the GTE predicate on the "ttft_ms" field.
func TtftMsGTE(v float64) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldGTE(FieldTtftMs, v))
}

// TtftMsLT applies the LT predicate on the "ttft_ms" field.
func TtftMsLT(v float64) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldLT(FieldTtftMs, v))
}

// TtftMsLTE applies the LTE predicate on the "ttft_ms" field.
func TtftMsLTE(v float64) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldLTE(FieldTtftMs, v))
}

// TtftMsIsNil applies the IsNil predicate on the "ttft_ms" field.
func TtftMsIsNil() predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldIsNull(FieldTtftMs))
}

// TtftMsNotNil applies the NotNil predicate on the "ttft_ms" field.
func TtftMsNotNil() predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNotNull(FieldTtftMs))
}

// TotalMsEQ applies the EQ predicate on the "total_ms" field.
func TotalMsEQ(v float64) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldEQ(FieldTotalMs, v))
}

// TotalMsNEQ applies the NEQ predicate on the "total_ms" field.
func TotalMsNEQ(v float64) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNEQ(FieldTotalMs, v))
}

// TotalMsIn applies the In predicate on the "total_ms" field.
func TotalMsIn(vs ...float64) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldIn(FieldTotalMs, vs...))
}

// TotalMsNotIn applies the NotIn predicate on the "total_ms" field.
func TotalMsNotIn(vs ...float64) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNotIn(FieldTotalMs, vs...))
}

// TotalMsGT applies the GT predicate on the "total_ms" field.
func TotalMsGT(v float64) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldGT(FieldTotalMs, v))
}

// TotalMsGTE applies the GTE predicate on the "total_ms" field.
func TotalMsGTE(v float64) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldGTE(FieldTotalMs, v))
}

// TotalMsLT applies the LT predicate on the "total_ms" field.
func TotalMsLT(v float64) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldLT(FieldTotalMs, v))
}

// TotalMsLTE applies the LTE predicate on the "total_ms" field.
func TotalMsLTE(v float64) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldLTE(FieldTotalMs, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldContainsFold(FieldErrorMessage, v))
}

// ScheduleKeyEQ applies the EQ predicate on the "schedule_key" field.
func ScheduleKeyEQ(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldEQ(FieldScheduleKey, v))
}

// ScheduleKeyNEQ applies the NEQ predicate on the "schedule_key" field.
func ScheduleKeyNEQ(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNEQ(FieldScheduleKey, v))
}

// ScheduleKeyIn applies the In predicate on the "schedule_key" field.
func ScheduleKeyIn(vs ...string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldIn(FieldScheduleKey, vs...))
}

// ScheduleKeyNotIn applies the NotIn predicate on the "schedule_key" field.
func ScheduleKeyNotIn(vs ...string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNotIn(FieldScheduleKey, vs...))
}

// ScheduleKeyGT applies the GT predicate on the "schedule_key" field.
func ScheduleKeyGT(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldGT(FieldScheduleKey, v))
}

// ScheduleKeyGTE applies the GTE predicate on the "schedule_key" field.
func ScheduleKeyGTE(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldGTE(FieldScheduleKey, v))
}

// ScheduleKeyLT applies the LT predicate on the "schedule_key" field.
func ScheduleKeyLT(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldLT(FieldScheduleKey, v))
}

// ScheduleKeyLTE applies the LTE predicate on the "schedule_key" field.
func ScheduleKeyLTE(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldLTE(FieldScheduleKey, v))
}

// ScheduleKeyContains applies the Contains predicate on the "schedule_key" field.
func ScheduleKeyContains(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldContains(FieldScheduleKey, v))
}

// ScheduleKeyHasPrefix applies the HasPrefix predicate on the "schedule_key" field.
func ScheduleKeyHasPrefix(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldHasPrefix(FieldScheduleKey, v))
}

// ScheduleKeyHasSuffix applies the HasSuffix predicate on the "schedule_key" field.
func ScheduleKeyHasSuffix(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldHasSuffix(FieldScheduleKey, v))
}

// ScheduleKeyIsNil applies the IsNil predicate on the "schedule_key" field.
func ScheduleKeyIsNil() predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldIsNull(FieldScheduleKey))
}

// ScheduleKeyNotNil applies the NotNil predicate on the "schedule_key" field.
func ScheduleKeyNotNil() predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNotNull(FieldScheduleKey))
}

// ScheduleKeyEqualFold applies the EqualFold predicate on the "schedule_key" field.
func ScheduleKeyEqualFold(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldEqualFold(FieldScheduleKey, v))
}

// ScheduleKeyContainsFold applies the ContainsFold predicate on the "schedule_key" field.
func ScheduleKeyContainsFold(v string) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldContainsFold(FieldScheduleKey, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldLTE(FieldStartedAt, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.FieldNotNull(FieldCompletedAt))
}

// HasChannel applies the HasEdge predicate on the "channel" edge.
func HasChannel() predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ChannelTable, ChannelColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChannelWith applies the HasEdge predicate on the "channel" edge with a given conditions (other predicates).
func HasChannelWith(preds ...predicate.Channel) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(func(s *sql.Selector) {
		step := newChannelStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ChannelHealthProbeRun) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ChannelHealthProbeRun) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ChannelHealthProbeRun) predicate.ChannelHealthProbeRun {
	return predicate.ChannelHealthProbeRun(sql.NotPredicates(p))
}
