// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/channelhealthproberun"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ChannelHealthProbeRunUpdate is the builder for updating ChannelHealthProbeRun entities.
type ChannelHealthProbeRunUpdate struct {
	config
	hooks     []Hook
	mutation  *ChannelHealthProbeRunMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ChannelHealthProbeRunUpdate builder.
func (_u *ChannelHealthProbeRunUpdate) Where(ps ...predicate.ChannelHealthProbeRun) *ChannelHealthProbeRunUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChannelHealthProbeRunUpdate) SetUpdatedAt(v time.Time) *ChannelHealthProbeRunUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ChannelHealthProbeRunUpdate) SetStatus(v channelhealthproberun.Status) *ChannelHealthProbeRunUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ChannelHealthProbeRunUpdate) SetNillableStatus(v *channelhealthproberun.Status) *ChannelHealthProbeRunUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTtfbMs sets the "ttfb_ms" field.
func (_u *ChannelHealthProbeRunUpdate) SetTtfbMs(v float64) *ChannelHealthProbeRunUpdate {
	_u.mutation.ResetTtfbMs()
	_u.mutation.SetTtfbMs(v)
	return _u
}

// SetNillableTtfbMs sets the "ttfb_ms" field if the given value is not nil.
func (_u *ChannelHealthProbeRunUpdate) SetNillableTtfbMs(v *float64) *ChannelHealthProbeRunUpdate {
	if v != nil {
		_u.SetTtfbMs(*v)
	}
	return _u
}

// AddTtfbMs adds value to the "ttfb_ms" field.
func (_u *ChannelHealthProbeRunUpdate) AddTtfbMs(v float64) *ChannelHealthProbeRunUpdate {
	_u.mutation.AddTtfbMs(v)
	return _u
}

// ClearTtfbMs clears the value of the "ttfb_ms" field.
func (_u *ChannelHealthProbeRunUpdate) ClearTtfbMs() *ChannelHealthProbeRunUpdate {
	_u.mutation.ClearTtfbMs()
	return _u
}

// SetTtftMs sets the "ttft_ms" field.
func (_u *ChannelHealthProbeRunUpdate) SetTtftMs(v float64) *ChannelHealthProbeRunUpdate {
	_u.mutation.ResetTtftMs()
	_u.mutation.SetTtftMs(v)
	return _u
}

// SetNillableTtftMs sets the "ttft_ms" field if the given value is not nil.
func (_u *ChannelHealthProbeRunUpdate) SetNillableTtftMs(v *float64) *ChannelHealthProbeRunUpdate {
	if v != nil {
		_u.SetTtftMs(*v)
	}
	return _u
}

// AddTtftMs adds value to the "ttft_ms" field.
func (_u *ChannelHealthProbeRunUpdate) AddTtftMs(v float64) *ChannelHealthProbeRunUpdate {
	_u.mutation.AddTtftMs(v)
	return _u
}

// ClearTtftMs clears the value of the "ttft_ms" field.
func (_u *ChannelHealthProbeRunUpdate) ClearTtftMs() *ChannelHealthProbeRunUpdate {
	_u.mutation.ClearTtftMs()
	return _u
}

// SetTotalMs sets the "total_ms" field.
func (_u *ChannelHealthProbeRunUpdate) SetTotalMs(v float64) *ChannelHealthProbeRunUpdate {
	_u.mutation.ResetTotalMs()
	_u.mutation.SetTotalMs(v)
	return _u
}

// SetNillableTotalMs sets the "total_ms" field if the given value is not nil.
func (_u *ChannelHealthProbeRunUpdate) SetNillableTotalMs(v *float64) *ChannelHealthProbeRunUpdate {
	if v != nil {
		_u.SetTotalMs(*v)
	}
	return _u
}

// AddTotalMs adds value to the "total_ms" field.
func (_u *ChannelHealthProbeRunUpdate) AddTotalMs(v float64) *ChannelHealthProbeRunUpdate {
	_u.mutation.AddTotalMs(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *ChannelHealthProbeRunUpdate) SetErrorMessage(v string) *ChannelHealthProbeRunUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *ChannelHealthProbeRunUpdate) SetNillableErrorMessage(v *string) *ChannelHealthProbeRunUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *ChannelHealthProbeRunUpdate) ClearErrorMessage() *ChannelHealthProbeRunUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *ChannelHealthProbeRunUpdate) SetCompletedAt(v time.Time) *ChannelHealthProbeRunUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *ChannelHealthProbeRunUpdate) SetNillableCompletedAt(v *time.Time) *ChannelHealthProbeRunUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *ChannelHealthProbeRunUpdate) ClearCompletedAt() *ChannelHealthProbeRunUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the ChannelHealthProbeRunMutation object of the builder.
func (_u *ChannelHealthProbeRunUpdate) Mutation() *ChannelHealthProbeRunMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChannelHealthProbeRunUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelHealthProbeRunUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChannelHealthProbeRunUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelHealthProbeRunUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChannelHealthProbeRunUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if channelhealthproberun.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized channelhealthproberun.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := channelhealthproberun.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelHealthProbeRunUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := channelhealthproberun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ChannelHealthProbeRun.status": %w`, err)}
		}
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelHealthProbeRun.channel"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ChannelHealthProbeRunUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ChannelHealthProbeRunUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ChannelHealthProbeRunUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channelhealthproberun.Table, channelhealthproberun.Columns, sqlgraph.NewFieldSpec(channelhealthproberun.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(channelhealthproberun.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(channelhealthproberun.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TtfbMs(); ok {
		_spec.SetField(channelhealthproberun.FieldTtfbMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTtfbMs(); ok {
		_spec.AddField(channelhealthproberun.FieldTtfbMs, field.TypeFloat64, value)
	}
	if _u.mutation.TtfbMsCleared() {
		_spec.ClearField(channelhealthproberun.FieldTtfbMs, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TtftMs(); ok {
		_spec.SetField(channelhealthproberun.FieldTtftMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTtftMs(); ok {
		_spec.AddField(channelhealthproberun.FieldTtftMs, field.TypeFloat64, value)
	}
	if _u.mutation.TtftMsCleared() {
		_spec.ClearField(channelhealthproberun.FieldTtftMs, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TotalMs(); ok {
		_spec.SetField(channelhealthproberun.FieldTotalMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalMs(); ok {
		_spec.AddField(channelhealthproberun.FieldTotalMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(channelhealthproberun.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(channelhealthproberun.FieldErrorMessage, field.TypeString)
	}
	if _u.mutation.ScheduleKeyCleared() {
		_spec.ClearField(channelhealthproberun.FieldScheduleKey, field.TypeString)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(channelhealthproberun.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(channelhealthproberun.FieldCompletedAt, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channelhealthproberun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChannelHealthProbeRunUpdateOne is the builder for updating a single ChannelHealthProbeRun entity.
type ChannelHealthProbeRunUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ChannelHealthProbeRunMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChannelHealthProbeRunUpdateOne) SetUpdatedAt(v time.Time) *ChannelHealthProbeRunUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ChannelHealthProbeRunUpdateOne) SetStatus(v channelhealthproberun.Status) *ChannelHealthProbeRunUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ChannelHealthProbeRunUpdateOne) SetNillableStatus(v *channelhealthproberun.Status) *ChannelHealthProbeRunUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTtfbMs sets the "ttfb_ms" field.
func (_u *ChannelHealthProbeRunUpdateOne) SetTtfbMs(v float64) *ChannelHealthProbeRunUpdateOne {
	_u.mutation.ResetTtfbMs()
	_u.mutation.SetTtfbMs(v)
	return _u
}

// SetNillableTtfbMs sets the "ttfb_ms" field if the given value is not nil.
func (_u *ChannelHealthProbeRunUpdateOne) SetNillableTtfbMs(v *float64) *ChannelHealthProbeRunUpdateOne {
	if v != nil {
		_u.SetTtfbMs(*v)
	}
	return _u
}

// AddTtfbMs adds value to the "ttfb_ms" field.
func (_u *ChannelHealthProbeRunUpdateOne) AddTtfbMs(v float64) *ChannelHealthProbeRunUpdateOne {
	_u.mutation.AddTtfbMs(v)
	return _u
}

// ClearTtfbMs clears the value of the "ttfb_ms" field.
func (_u *ChannelHealthProbeRunUpdateOne) ClearTtfbMs() *ChannelHealthProbeRunUpdateOne {
	_u.mutation.ClearTtfbMs()
	return _u
}

// SetTtftMs sets the "ttft_ms" field.
func (_u *ChannelHealthProbeRunUpdateOne) SetTtftMs(v float64) *ChannelHealthProbeRunUpdateOne {
	_u.mutation.ResetTtftMs()
	_u.mutation.SetTtftMs(v)
	return _u
}

// SetNillableTtftMs sets the "ttft_ms" field if the given value is not nil.
func (_u *ChannelHealthProbeRunUpdateOne) SetNillableTtftMs(v *float64) *ChannelHealthProbeRunUpdateOne {
	if v != nil {
		_u.SetTtftMs(*v)
	}
	return _u
}

// AddTtftMs adds value to the "ttft_ms" field.
func (_u *ChannelHealthProbeRunUpdateOne) AddTtftMs(v float64) *ChannelHealthProbeRunUpdateOne {
	_u.mutation.AddTtftMs(v)
	return _u
}

// ClearTtftMs clears the value of the "ttft_ms" field.
func (_u *ChannelHealthProbeRunUpdateOne) ClearTtftMs() *ChannelHealthProbeRunUpdateOne {
	_u.mutation.ClearTtftMs()
	return _u
}

// SetTotalMs sets the "total_ms" field.
func (_u *ChannelHealthProbeRunUpdateOne) SetTotalMs(v float64) *ChannelHealthProbeRunUpdateOne {
	_u.mutation.ResetTotalMs()
	_u.mutation.SetTotalMs(v)
	return _u
}

// SetNillableTotalMs sets the "total_ms" field if the given value is not nil.
func (_u *ChannelHealthProbeRunUpdateOne) SetNillableTotalMs(v *float64) *ChannelHealthProbeRunUpdateOne {
	if v != nil {
		_u.SetTotalMs(*v)
	}
	return _u
}

// AddTotalMs adds value to the "total_ms" field.
func (_u *ChannelHealthProbeRunUpdateOne) AddTotalMs(v float64) *ChannelHealthProbeRunUpdateOne {
	_u.mutation.AddTotalMs(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *ChannelHealthProbeRunUpdateOne) SetErrorMessage(v string) *ChannelHealthProbeRunUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *ChannelHealthProbeRunUpdateOne) SetNillableErrorMessage(v *string) *ChannelHealthProbeRunUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *ChannelHealthProbeRunUpdateOne) ClearErrorMessage() *ChannelHealthProbeRunUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *ChannelHealthProbeRunUpdateOne) SetCompletedAt(v time.Time) *ChannelHealthProbeRunUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *ChannelHealthProbeRunUpdateOne) SetNillableCompletedAt(v *time.Time) *ChannelHealthProbeRunUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *ChannelHealthProbeRunUpdateOne) ClearCompletedAt() *ChannelHealthProbeRunUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the ChannelHealthProbeRunMutation object of the builder.
func (_u *ChannelHealthProbeRunUpdateOne) Mutation() *ChannelHealthProbeRunMutation {
	return _u.mutation
}

// Where appends a list predicates to the ChannelHealthProbeRunUpdate builder.
func (_u *ChannelHealthProbeRunUpdateOne) Where(ps ...predicate.ChannelHealthProbeRun) *ChannelHealthProbeRunUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChannelHealthProbeRunUpdateOne) Select(field string, fields ...string) *ChannelHealthProbeRunUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChannelHealthProbeRun entity.
func (_u *ChannelHealthProbeRunUpdateOne) Save(ctx context.Context) (*ChannelHealthProbeRun, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelHealthProbeRunUpdateOne) SaveX(ctx context.Context) *ChannelHealthProbeRun {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChannelHealthProbeRunUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelHealthProbeRunUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChannelHealthProbeRunUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if channelhealthproberun.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized channelhealthproberun.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := channelhealthproberun.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelHealthProbeRunUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := channelhealthproberun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ChannelHealthProbeRun.status": %w`, err)}
		}
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelHealthProbeRun.channel"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ChannelHealthProbeRunUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ChannelHealthProbeRunUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ChannelHealthProbeRunUpdateOne) sqlSave(ctx context.Context) (_node *ChannelHealthProbeRun, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channelhealthproberun.Table, channelhealthproberun.Columns, sqlgraph.NewFieldSpec(channelhealthproberun.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChannelHealthProbeRun.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, channelhealthproberun.FieldID)
		for _, f := range fields {
			if !channelhealthproberun.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != channelhealthproberun.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(channelhealthproberun.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(channelhealthproberun.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TtfbMs(); ok {
		_spec.SetField(channelhealthproberun.FieldTtfbMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTtfbMs(); ok {
		_spec.AddField(channelhealthproberun.FieldTtfbMs, field.TypeFloat64, value)
	}
	if _u.mutation.TtfbMsCleared() {
		_spec.ClearField(channelhealthproberun.FieldTtfbMs, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TtftMs(); ok {
		_spec.SetField(channelhealthproberun.FieldTtftMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTtftMs(); ok {
		_spec.AddField(channelhealthproberun.FieldTtftMs, field.TypeFloat64, value)
	}
	if _u.mutation.TtftMsCleared() {
		_spec.ClearField(channelhealthproberun.FieldTtftMs, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TotalMs(); ok {
		_spec.SetField(channelhealthproberun.FieldTotalMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalMs(); ok {
		_spec.AddField(channelhealthproberun.FieldTotalMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(channelhealthproberun.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(channelhealthproberun.FieldErrorMessage, field.TypeString)
	}
	if _u.mutation.ScheduleKeyCleared() {
		_spec.ClearField(channelhealthproberun.FieldScheduleKey, field.TypeString)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(channelhealthproberun.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(channelhealthproberun.FieldCompletedAt, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ChannelHealthProbeRun{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channelhealthproberun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
