// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/apikey"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/channelcalleraclmember"
)

// ChannelCallerACLMember is the model entity for the ChannelCallerACLMember schema.
type ChannelCallerACLMember struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ChannelID holds the value of the "channel_id" field.
	ChannelID int `json:"channel_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int `json:"api_key_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChannelCallerACLMemberQuery when eager-loading is set.
	Edges        ChannelCallerACLMemberEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ChannelCallerACLMemberEdges holds the relations/edges for other nodes in the graph.
type ChannelCallerACLMemberEdges struct {
	// Channel holds the value of the channel edge.
	Channel *Channel `json:"channel,omitempty"`
	// APIKey holds the value of the api_key edge.
	APIKey *APIKey `json:"api_key,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	// totalCount holds the count of the edges above.
	totalCount [2]map[string]int
}

// ChannelOrErr returns the Channel value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChannelCallerACLMemberEdges) ChannelOrErr() (*Channel, error) {
	if e.Channel != nil {
		return e.Channel, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: channel.Label}
	}
	return nil, &NotLoadedError{edge: "channel"}
}

// APIKeyOrErr returns the APIKey value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChannelCallerACLMemberEdges) APIKeyOrErr() (*APIKey, error) {
	if e.APIKey != nil {
		return e.APIKey, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: apikey.Label}
	}
	return nil, &NotLoadedError{edge: "api_key"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChannelCallerACLMember) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case channelcalleraclmember.FieldID, channelcalleraclmember.FieldChannelID, channelcalleraclmember.FieldAPIKeyID:
			values[i] = new(sql.NullInt64)
		case channelcalleraclmember.FieldCreatedAt, channelcalleraclmember.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChannelCallerACLMember fields.
func (_m *ChannelCallerACLMember) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case channelcalleraclmember.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case channelcalleraclmember.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case channelcalleraclmember.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case channelcalleraclmember.FieldChannelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value.Valid {
				_m.ChannelID = int(value.Int64)
			}
		case channelcalleraclmember.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChannelCallerACLMember.
// This includes values selected through modifiers, order, etc.
func (_m *ChannelCallerACLMember) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChannel queries the "channel" edge of the ChannelCallerACLMember entity.
func (_m *ChannelCallerACLMember) QueryChannel() *ChannelQuery {
	return NewChannelCallerACLMemberClient(_m.config).QueryChannel(_m)
}

// QueryAPIKey queries the "api_key" edge of the ChannelCallerACLMember entity.
func (_m *ChannelCallerACLMember) QueryAPIKey() *APIKeyQuery {
	return NewChannelCallerACLMemberClient(_m.config).QueryAPIKey(_m)
}

// Update returns a builder for updating this ChannelCallerACLMember.
// Note that you need to call ChannelCallerACLMember.Unwrap() before calling this method if this ChannelCallerACLMember
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChannelCallerACLMember) Update() *ChannelCallerACLMemberUpdateOne {
	return NewChannelCallerACLMemberClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChannelCallerACLMember entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChannelCallerACLMember) Unwrap() *ChannelCallerACLMember {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChannelCallerACLMember is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChannelCallerACLMember) String() string {
	var builder strings.Builder
	builder.WriteString("ChannelCallerACLMember(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("channel_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChannelID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteByte(')')
	return builder.String()
}

// ChannelCallerACLMembers is a parsable slice of ChannelCallerACLMember.
type ChannelCallerACLMembers []*ChannelCallerACLMember
