// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/apikey"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/channelcalleraclmember"
)

// ChannelCallerACLMemberCreate is the builder for creating a ChannelCallerACLMember entity.
type ChannelCallerACLMemberCreate struct {
	config
	mutation *ChannelCallerACLMemberMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChannelCallerACLMemberCreate) SetCreatedAt(v time.Time) *ChannelCallerACLMemberCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChannelCallerACLMemberCreate) SetNillableCreatedAt(v *time.Time) *ChannelCallerACLMemberCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ChannelCallerACLMemberCreate) SetUpdatedAt(v time.Time) *ChannelCallerACLMemberCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ChannelCallerACLMemberCreate) SetNillableUpdatedAt(v *time.Time) *ChannelCallerACLMemberCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetChannelID sets the "channel_id" field.
func (_c *ChannelCallerACLMemberCreate) SetChannelID(v int) *ChannelCallerACLMemberCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *ChannelCallerACLMemberCreate) SetAPIKeyID(v int) *ChannelCallerACLMemberCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_c *ChannelCallerACLMemberCreate) SetChannel(v *Channel) *ChannelCallerACLMemberCreate {
	return _c.SetChannelID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_c *ChannelCallerACLMemberCreate) SetAPIKey(v *APIKey) *ChannelCallerACLMemberCreate {
	return _c.SetAPIKeyID(v.ID)
}

// Mutation returns the ChannelCallerACLMemberMutation object of the builder.
func (_c *ChannelCallerACLMemberCreate) Mutation() *ChannelCallerACLMemberMutation {
	return _c.mutation
}

// Save creates the ChannelCallerACLMember in the database.
func (_c *ChannelCallerACLMemberCreate) Save(ctx context.Context) (*ChannelCallerACLMember, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChannelCallerACLMemberCreate) SaveX(ctx context.Context) *ChannelCallerACLMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelCallerACLMemberCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelCallerACLMemberCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChannelCallerACLMemberCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := channelcalleraclmember.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := channelcalleraclmember.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChannelCallerACLMemberCreate) check() error {
	if _, ok := _c.mutation.ChannelID(); !ok {
		return &ValidationError{Name: "channel_id", err: errors.New(`ent: missing required field "ChannelCallerACLMember.channel_id"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "ChannelCallerACLMember.api_key_id"`)}
	}
	if len(_c.mutation.ChannelIDs()) == 0 {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required edge "ChannelCallerACLMember.channel"`)}
	}
	if len(_c.mutation.APIKeyIDs()) == 0 {
		return &ValidationError{Name: "api_key", err: errors.New(`ent: missing required edge "ChannelCallerACLMember.api_key"`)}
	}
	return nil
}

func (_c *ChannelCallerACLMemberCreate) sqlSave(ctx context.Context) (*ChannelCallerACLMember, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChannelCallerACLMemberCreate) createSpec() (*ChannelCallerACLMember, *sqlgraph.CreateSpec) {
	var (
		_node = &ChannelCallerACLMember{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(channelcalleraclmember.Table, sqlgraph.NewFieldSpec(channelcalleraclmember.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(channelcalleraclmember.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(channelcalleraclmember.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelcalleraclmember.ChannelTable,
			Columns: []string{channelcalleraclmember.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChannelID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelcalleraclmember.APIKeyTable,
			Columns: []string{channelcalleraclmember.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.APIKeyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChannelCallerACLMember.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChannelCallerACLMemberUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ChannelCallerACLMemberCreate) OnConflict(opts ...sql.ConflictOption) *ChannelCallerACLMemberUpsertOne {
	_c.conflict = opts
	return &ChannelCallerACLMemberUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChannelCallerACLMember.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChannelCallerACLMemberCreate) OnConflictColumns(columns ...string) *ChannelCallerACLMemberUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChannelCallerACLMemberUpsertOne{
		create: _c,
	}
}

type (
	// ChannelCallerACLMemberUpsertOne is the builder for "upsert"-ing
	//  one ChannelCallerACLMember node.
	ChannelCallerACLMemberUpsertOne struct {
		create *ChannelCallerACLMemberCreate
	}

	// ChannelCallerACLMemberUpsert is the "OnConflict" setter.
	ChannelCallerACLMemberUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ChannelCallerACLMemberUpsert) SetUpdatedAt(v time.Time) *ChannelCallerACLMemberUpsert {
	u.Set(channelcalleraclmember.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChannelCallerACLMemberUpsert) UpdateUpdatedAt() *ChannelCallerACLMemberUpsert {
	u.SetExcluded(channelcalleraclmember.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ChannelCallerACLMember.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChannelCallerACLMemberUpsertOne) UpdateNewValues() *ChannelCallerACLMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(channelcalleraclmember.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.ChannelID(); exists {
			s.SetIgnore(channelcalleraclmember.FieldChannelID)
		}
		if _, exists := u.create.mutation.APIKeyID(); exists {
			s.SetIgnore(channelcalleraclmember.FieldAPIKeyID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChannelCallerACLMember.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChannelCallerACLMemberUpsertOne) Ignore() *ChannelCallerACLMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChannelCallerACLMemberUpsertOne) DoNothing() *ChannelCallerACLMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChannelCallerACLMemberCreate.OnConflict
// documentation for more info.
func (u *ChannelCallerACLMemberUpsertOne) Update(set func(*ChannelCallerACLMemberUpsert)) *ChannelCallerACLMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChannelCallerACLMemberUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChannelCallerACLMemberUpsertOne) SetUpdatedAt(v time.Time) *ChannelCallerACLMemberUpsertOne {
	return u.Update(func(s *ChannelCallerACLMemberUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChannelCallerACLMemberUpsertOne) UpdateUpdatedAt() *ChannelCallerACLMemberUpsertOne {
	return u.Update(func(s *ChannelCallerACLMemberUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ChannelCallerACLMemberUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChannelCallerACLMemberCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChannelCallerACLMemberUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChannelCallerACLMemberUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChannelCallerACLMemberUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChannelCallerACLMemberCreateBulk is the builder for creating many ChannelCallerACLMember entities in bulk.
type ChannelCallerACLMemberCreateBulk struct {
	config
	err      error
	builders []*ChannelCallerACLMemberCreate
	conflict []sql.ConflictOption
}

// Save creates the ChannelCallerACLMember entities in the database.
func (_c *ChannelCallerACLMemberCreateBulk) Save(ctx context.Context) ([]*ChannelCallerACLMember, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChannelCallerACLMember, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChannelCallerACLMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChannelCallerACLMemberCreateBulk) SaveX(ctx context.Context) []*ChannelCallerACLMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelCallerACLMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelCallerACLMemberCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChannelCallerACLMember.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChannelCallerACLMemberUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ChannelCallerACLMemberCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChannelCallerACLMemberUpsertBulk {
	_c.conflict = opts
	return &ChannelCallerACLMemberUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChannelCallerACLMember.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChannelCallerACLMemberCreateBulk) OnConflictColumns(columns ...string) *ChannelCallerACLMemberUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChannelCallerACLMemberUpsertBulk{
		create: _c,
	}
}

// ChannelCallerACLMemberUpsertBulk is the builder for "upsert"-ing
// a bulk of ChannelCallerACLMember nodes.
type ChannelCallerACLMemberUpsertBulk struct {
	create *ChannelCallerACLMemberCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ChannelCallerACLMember.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChannelCallerACLMemberUpsertBulk) UpdateNewValues() *ChannelCallerACLMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(channelcalleraclmember.FieldCreatedAt)
			}
			if _, exists := b.mutation.ChannelID(); exists {
				s.SetIgnore(channelcalleraclmember.FieldChannelID)
			}
			if _, exists := b.mutation.APIKeyID(); exists {
				s.SetIgnore(channelcalleraclmember.FieldAPIKeyID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChannelCallerACLMember.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChannelCallerACLMemberUpsertBulk) Ignore() *ChannelCallerACLMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChannelCallerACLMemberUpsertBulk) DoNothing() *ChannelCallerACLMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChannelCallerACLMemberCreateBulk.OnConflict
// documentation for more info.
func (u *ChannelCallerACLMemberUpsertBulk) Update(set func(*ChannelCallerACLMemberUpsert)) *ChannelCallerACLMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChannelCallerACLMemberUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChannelCallerACLMemberUpsertBulk) SetUpdatedAt(v time.Time) *ChannelCallerACLMemberUpsertBulk {
	return u.Update(func(s *ChannelCallerACLMemberUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChannelCallerACLMemberUpsertBulk) UpdateUpdatedAt() *ChannelCallerACLMemberUpsertBulk {
	return u.Update(func(s *ChannelCallerACLMemberUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ChannelCallerACLMemberUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ChannelCallerACLMemberCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChannelCallerACLMemberCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChannelCallerACLMemberUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
