// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/channelhealthproberun"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ChannelHealthProbeRunDelete is the builder for deleting a ChannelHealthProbeRun entity.
type ChannelHealthProbeRunDelete struct {
	config
	hooks    []Hook
	mutation *ChannelHealthProbeRunMutation
}

// Where appends a list predicates to the ChannelHealthProbeRunDelete builder.
func (_d *ChannelHealthProbeRunDelete) Where(ps ...predicate.ChannelHealthProbeRun) *ChannelHealthProbeRunDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ChannelHealthProbeRunDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChannelHealthProbeRunDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ChannelHealthProbeRunDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(channelhealthproberun.Table, sqlgraph.NewFieldSpec(channelhealthproberun.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ChannelHealthProbeRunDeleteOne is the builder for deleting a single ChannelHealthProbeRun entity.
type ChannelHealthProbeRunDeleteOne struct {
	_d *ChannelHealthProbeRunDelete
}

// Where appends a list predicates to the ChannelHealthProbeRunDelete builder.
func (_d *ChannelHealthProbeRunDeleteOne) Where(ps ...predicate.ChannelHealthProbeRun) *ChannelHealthProbeRunDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ChannelHealthProbeRunDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{channelhealthproberun.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChannelHealthProbeRunDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
