// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/channelhealthproberun"
)

// ChannelHealthProbeRunCreate is the builder for creating a ChannelHealthProbeRun entity.
type ChannelHealthProbeRunCreate struct {
	config
	mutation *ChannelHealthProbeRunMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChannelHealthProbeRunCreate) SetCreatedAt(v time.Time) *ChannelHealthProbeRunCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChannelHealthProbeRunCreate) SetNillableCreatedAt(v *time.Time) *ChannelHealthProbeRunCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ChannelHealthProbeRunCreate) SetUpdatedAt(v time.Time) *ChannelHealthProbeRunCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ChannelHealthProbeRunCreate) SetNillableUpdatedAt(v *time.Time) *ChannelHealthProbeRunCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetChannelID sets the "channel_id" field.
func (_c *ChannelHealthProbeRunCreate) SetChannelID(v int) *ChannelHealthProbeRunCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetModelID sets the "model_id" field.
func (_c *ChannelHealthProbeRunCreate) SetModelID(v string) *ChannelHealthProbeRunCreate {
	_c.mutation.SetModelID(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *ChannelHealthProbeRunCreate) SetSource(v channelhealthproberun.Source) *ChannelHealthProbeRunCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ChannelHealthProbeRunCreate) SetStatus(v channelhealthproberun.Status) *ChannelHealthProbeRunCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetStream sets the "stream" field.
func (_c *ChannelHealthProbeRunCreate) SetStream(v bool) *ChannelHealthProbeRunCreate {
	_c.mutation.SetStream(v)
	return _c
}

// SetTtfbMs sets the "ttfb_ms" field.
func (_c *ChannelHealthProbeRunCreate) SetTtfbMs(v float64) *ChannelHealthProbeRunCreate {
	_c.mutation.SetTtfbMs(v)
	return _c
}

// SetNillableTtfbMs sets the "ttfb_ms" field if the given value is not nil.
func (_c *ChannelHealthProbeRunCreate) SetNillableTtfbMs(v *float64) *ChannelHealthProbeRunCreate {
	if v != nil {
		_c.SetTtfbMs(*v)
	}
	return _c
}

// SetTtftMs sets the "ttft_ms" field.
func (_c *ChannelHealthProbeRunCreate) SetTtftMs(v float64) *ChannelHealthProbeRunCreate {
	_c.mutation.SetTtftMs(v)
	return _c
}

// SetNillableTtftMs sets the "ttft_ms" field if the given value is not nil.
func (_c *ChannelHealthProbeRunCreate) SetNillableTtftMs(v *float64) *ChannelHealthProbeRunCreate {
	if v != nil {
		_c.SetTtftMs(*v)
	}
	return _c
}

// SetTotalMs sets the "total_ms" field.
func (_c *ChannelHealthProbeRunCreate) SetTotalMs(v float64) *ChannelHealthProbeRunCreate {
	_c.mutation.SetTotalMs(v)
	return _c
}

// SetNillableTotalMs sets the "total_ms" field if the given value is not nil.
func (_c *ChannelHealthProbeRunCreate) SetNillableTotalMs(v *float64) *ChannelHealthProbeRunCreate {
	if v != nil {
		_c.SetTotalMs(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *ChannelHealthProbeRunCreate) SetErrorMessage(v string) *ChannelHealthProbeRunCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *ChannelHealthProbeRunCreate) SetNillableErrorMessage(v *string) *ChannelHealthProbeRunCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetScheduleKey sets the "schedule_key" field.
func (_c *ChannelHealthProbeRunCreate) SetScheduleKey(v string) *ChannelHealthProbeRunCreate {
	_c.mutation.SetScheduleKey(v)
	return _c
}

// SetNillableScheduleKey sets the "schedule_key" field if the given value is not nil.
func (_c *ChannelHealthProbeRunCreate) SetNillableScheduleKey(v *string) *ChannelHealthProbeRunCreate {
	if v != nil {
		_c.SetScheduleKey(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *ChannelHealthProbeRunCreate) SetStartedAt(v time.Time) *ChannelHealthProbeRunCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *ChannelHealthProbeRunCreate) SetCompletedAt(v time.Time) *ChannelHealthProbeRunCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *ChannelHealthProbeRunCreate) SetNillableCompletedAt(v *time.Time) *ChannelHealthProbeRunCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_c *ChannelHealthProbeRunCreate) SetChannel(v *Channel) *ChannelHealthProbeRunCreate {
	return _c.SetChannelID(v.ID)
}

// Mutation returns the ChannelHealthProbeRunMutation object of the builder.
func (_c *ChannelHealthProbeRunCreate) Mutation() *ChannelHealthProbeRunMutation {
	return _c.mutation
}

// Save creates the ChannelHealthProbeRun in the database.
func (_c *ChannelHealthProbeRunCreate) Save(ctx context.Context) (*ChannelHealthProbeRun, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChannelHealthProbeRunCreate) SaveX(ctx context.Context) *ChannelHealthProbeRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelHealthProbeRunCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelHealthProbeRunCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChannelHealthProbeRunCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if channelhealthproberun.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized channelhealthproberun.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := channelhealthproberun.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if channelhealthproberun.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized channelhealthproberun.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := channelhealthproberun.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.TotalMs(); !ok {
		v := channelhealthproberun.DefaultTotalMs
		_c.mutation.SetTotalMs(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChannelHealthProbeRunCreate) check() error {
	if _, ok := _c.mutation.ChannelID(); !ok {
		return &ValidationError{Name: "channel_id", err: errors.New(`ent: missing required field "ChannelHealthProbeRun.channel_id"`)}
	}
	if _, ok := _c.mutation.ModelID(); !ok {
		return &ValidationError{Name: "model_id", err: errors.New(`ent: missing required field "ChannelHealthProbeRun.model_id"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "ChannelHealthProbeRun.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := channelhealthproberun.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "ChannelHealthProbeRun.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ChannelHealthProbeRun.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := channelhealthproberun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ChannelHealthProbeRun.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Stream(); !ok {
		return &ValidationError{Name: "stream", err: errors.New(`ent: missing required field "ChannelHealthProbeRun.stream"`)}
	}
	if _, ok := _c.mutation.TotalMs(); !ok {
		return &ValidationError{Name: "total_ms", err: errors.New(`ent: missing required field "ChannelHealthProbeRun.total_ms"`)}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "ChannelHealthProbeRun.started_at"`)}
	}
	if len(_c.mutation.ChannelIDs()) == 0 {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required edge "ChannelHealthProbeRun.channel"`)}
	}
	return nil
}

func (_c *ChannelHealthProbeRunCreate) sqlSave(ctx context.Context) (*ChannelHealthProbeRun, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChannelHealthProbeRunCreate) createSpec() (*ChannelHealthProbeRun, *sqlgraph.CreateSpec) {
	var (
		_node = &ChannelHealthProbeRun{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(channelhealthproberun.Table, sqlgraph.NewFieldSpec(channelhealthproberun.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(channelhealthproberun.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(channelhealthproberun.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ModelID(); ok {
		_spec.SetField(channelhealthproberun.FieldModelID, field.TypeString, value)
		_node.ModelID = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(channelhealthproberun.FieldSource, field.TypeEnum, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(channelhealthproberun.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Stream(); ok {
		_spec.SetField(channelhealthproberun.FieldStream, field.TypeBool, value)
		_node.Stream = value
	}
	if value, ok := _c.mutation.TtfbMs(); ok {
		_spec.SetField(channelhealthproberun.FieldTtfbMs, field.TypeFloat64, value)
		_node.TtfbMs = &value
	}
	if value, ok := _c.mutation.TtftMs(); ok {
		_spec.SetField(channelhealthproberun.FieldTtftMs, field.TypeFloat64, value)
		_node.TtftMs = &value
	}
	if value, ok := _c.mutation.TotalMs(); ok {
		_spec.SetField(channelhealthproberun.FieldTotalMs, field.TypeFloat64, value)
		_node.TotalMs = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(channelhealthproberun.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.ScheduleKey(); ok {
		_spec.SetField(channelhealthproberun.FieldScheduleKey, field.TypeString, value)
		_node.ScheduleKey = &value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(channelhealthproberun.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(channelhealthproberun.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if nodes := _c.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelhealthproberun.ChannelTable,
			Columns: []string{channelhealthproberun.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChannelID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChannelHealthProbeRun.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChannelHealthProbeRunUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ChannelHealthProbeRunCreate) OnConflict(opts ...sql.ConflictOption) *ChannelHealthProbeRunUpsertOne {
	_c.conflict = opts
	return &ChannelHealthProbeRunUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChannelHealthProbeRun.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChannelHealthProbeRunCreate) OnConflictColumns(columns ...string) *ChannelHealthProbeRunUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChannelHealthProbeRunUpsertOne{
		create: _c,
	}
}

type (
	// ChannelHealthProbeRunUpsertOne is the builder for "upsert"-ing
	//  one ChannelHealthProbeRun node.
	ChannelHealthProbeRunUpsertOne struct {
		create *ChannelHealthProbeRunCreate
	}

	// ChannelHealthProbeRunUpsert is the "OnConflict" setter.
	ChannelHealthProbeRunUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ChannelHealthProbeRunUpsert) SetUpdatedAt(v time.Time) *ChannelHealthProbeRunUpsert {
	u.Set(channelhealthproberun.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChannelHealthProbeRunUpsert) UpdateUpdatedAt() *ChannelHealthProbeRunUpsert {
	u.SetExcluded(channelhealthproberun.FieldUpdatedAt)
	return u
}

// SetStatus sets the "status" field.
func (u *ChannelHealthProbeRunUpsert) SetStatus(v channelhealthproberun.Status) *ChannelHealthProbeRunUpsert {
	u.Set(channelhealthproberun.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChannelHealthProbeRunUpsert) UpdateStatus() *ChannelHealthProbeRunUpsert {
	u.SetExcluded(channelhealthproberun.FieldStatus)
	return u
}

// SetTtfbMs sets the "ttfb_ms" field.
func (u *ChannelHealthProbeRunUpsert) SetTtfbMs(v float64) *ChannelHealthProbeRunUpsert {
	u.Set(channelhealthproberun.FieldTtfbMs, v)
	return u
}

// UpdateTtfbMs sets the "ttfb_ms" field to the value that was provided on create.
func (u *ChannelHealthProbeRunUpsert) UpdateTtfbMs() *ChannelHealthProbeRunUpsert {
	u.SetExcluded(channelhealthproberun.FieldTtfbMs)
	return u
}

// AddTtfbMs adds v to the "ttfb_ms" field.
func (u *ChannelHealthProbeRunUpsert) AddTtfbMs(v float64) *ChannelHealthProbeRunUpsert {
	u.Add(channelhealthproberun.FieldTtfbMs, v)
	return u
}

// ClearTtfbMs clears the value of the "ttfb_ms" field.
func (u *ChannelHealthProbeRunUpsert) ClearTtfbMs() *ChannelHealthProbeRunUpsert {
	u.SetNull(channelhealthproberun.FieldTtfbMs)
	return u
}

// SetTtftMs sets the "ttft_ms" field.
func (u *ChannelHealthProbeRunUpsert) SetTtftMs(v float64) *ChannelHealthProbeRunUpsert {
	u.Set(channelhealthproberun.FieldTtftMs, v)
	return u
}

// UpdateTtftMs sets the "ttft_ms" field to the value that was provided on create.
func (u *ChannelHealthProbeRunUpsert) UpdateTtftMs() *ChannelHealthProbeRunUpsert {
	u.SetExcluded(channelhealthproberun.FieldTtftMs)
	return u
}

// AddTtftMs adds v to the "ttft_ms" field.
func (u *ChannelHealthProbeRunUpsert) AddTtftMs(v float64) *ChannelHealthProbeRunUpsert {
	u.Add(channelhealthproberun.FieldTtftMs, v)
	return u
}

// ClearTtftMs clears the value of the "ttft_ms" field.
func (u *ChannelHealthProbeRunUpsert) ClearTtftMs() *ChannelHealthProbeRunUpsert {
	u.SetNull(channelhealthproberun.FieldTtftMs)
	return u
}

// SetTotalMs sets the "total_ms" field.
func (u *ChannelHealthProbeRunUpsert) SetTotalMs(v float64) *ChannelHealthProbeRunUpsert {
	u.Set(channelhealthproberun.FieldTotalMs, v)
	return u
}

// UpdateTotalMs sets the "total_ms" field to the value that was provided on create.
func (u *ChannelHealthProbeRunUpsert) UpdateTotalMs() *ChannelHealthProbeRunUpsert {
	u.SetExcluded(channelhealthproberun.FieldTotalMs)
	return u
}

// AddTotalMs adds v to the "total_ms" field.
func (u *ChannelHealthProbeRunUpsert) AddTotalMs(v float64) *ChannelHealthProbeRunUpsert {
	u.Add(channelhealthproberun.FieldTotalMs, v)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *ChannelHealthProbeRunUpsert) SetErrorMessage(v string) *ChannelHealthProbeRunUpsert {
	u.Set(channelhealthproberun.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *ChannelHealthProbeRunUpsert) UpdateErrorMessage() *ChannelHealthProbeRunUpsert {
	u.SetExcluded(channelhealthproberun.FieldErrorMessage)
	return u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *ChannelHealthProbeRunUpsert) ClearErrorMessage() *ChannelHealthProbeRunUpsert {
	u.SetNull(channelhealthproberun.FieldErrorMessage)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *ChannelHealthProbeRunUpsert) SetCompletedAt(v time.Time) *ChannelHealthProbeRunUpsert {
	u.Set(channelhealthproberun.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *ChannelHealthProbeRunUpsert) UpdateCompletedAt() *ChannelHealthProbeRunUpsert {
	u.SetExcluded(channelhealthproberun.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *ChannelHealthProbeRunUpsert) ClearCompletedAt() *ChannelHealthProbeRunUpsert {
	u.SetNull(channelhealthproberun.FieldCompletedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ChannelHealthProbeRun.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChannelHealthProbeRunUpsertOne) UpdateNewValues() *ChannelHealthProbeRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(channelhealthproberun.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.ChannelID(); exists {
			s.SetIgnore(channelhealthproberun.FieldChannelID)
		}
		if _, exists := u.create.mutation.ModelID(); exists {
			s.SetIgnore(channelhealthproberun.FieldModelID)
		}
		if _, exists := u.create.mutation.Source(); exists {
			s.SetIgnore(channelhealthproberun.FieldSource)
		}
		if _, exists := u.create.mutation.Stream(); exists {
			s.SetIgnore(channelhealthproberun.FieldStream)
		}
		if _, exists := u.create.mutation.ScheduleKey(); exists {
			s.SetIgnore(channelhealthproberun.FieldScheduleKey)
		}
		if _, exists := u.create.mutation.StartedAt(); exists {
			s.SetIgnore(channelhealthproberun.FieldStartedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChannelHealthProbeRun.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChannelHealthProbeRunUpsertOne) Ignore() *ChannelHealthProbeRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChannelHealthProbeRunUpsertOne) DoNothing() *ChannelHealthProbeRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChannelHealthProbeRunCreate.OnConflict
// documentation for more info.
func (u *ChannelHealthProbeRunUpsertOne) Update(set func(*ChannelHealthProbeRunUpsert)) *ChannelHealthProbeRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChannelHealthProbeRunUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChannelHealthProbeRunUpsertOne) SetUpdatedAt(v time.Time) *ChannelHealthProbeRunUpsertOne {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChannelHealthProbeRunUpsertOne) UpdateUpdatedAt() *ChannelHealthProbeRunUpsertOne {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetStatus sets the "status" field.
func (u *ChannelHealthProbeRunUpsertOne) SetStatus(v channelhealthproberun.Status) *ChannelHealthProbeRunUpsertOne {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChannelHealthProbeRunUpsertOne) UpdateStatus() *ChannelHealthProbeRunUpsertOne {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.UpdateStatus()
	})
}

// SetTtfbMs sets the "ttfb_ms" field.
func (u *ChannelHealthProbeRunUpsertOne) SetTtfbMs(v float64) *ChannelHealthProbeRunUpsertOne {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.SetTtfbMs(v)
	})
}

// AddTtfbMs adds v to the "ttfb_ms" field.
func (u *ChannelHealthProbeRunUpsertOne) AddTtfbMs(v float64) *ChannelHealthProbeRunUpsertOne {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.AddTtfbMs(v)
	})
}

// UpdateTtfbMs sets the "ttfb_ms" field to the value that was provided on create.
func (u *ChannelHealthProbeRunUpsertOne) UpdateTtfbMs() *ChannelHealthProbeRunUpsertOne {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.UpdateTtfbMs()
	})
}

// ClearTtfbMs clears the value of the "ttfb_ms" field.
func (u *ChannelHealthProbeRunUpsertOne) ClearTtfbMs() *ChannelHealthProbeRunUpsertOne {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.ClearTtfbMs()
	})
}

// SetTtftMs sets the "ttft_ms" field.
func (u *ChannelHealthProbeRunUpsertOne) SetTtftMs(v float64) *ChannelHealthProbeRunUpsertOne {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.SetTtftMs(v)
	})
}

// AddTtftMs adds v to the "ttft_ms" field.
func (u *ChannelHealthProbeRunUpsertOne) AddTtftMs(v float64) *ChannelHealthProbeRunUpsertOne {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.AddTtftMs(v)
	})
}

// UpdateTtftMs sets the "ttft_ms" field to the value that was provided on create.
func (u *ChannelHealthProbeRunUpsertOne) UpdateTtftMs() *ChannelHealthProbeRunUpsertOne {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.UpdateTtftMs()
	})
}

// ClearTtftMs clears the value of the "ttft_ms" field.
func (u *ChannelHealthProbeRunUpsertOne) ClearTtftMs() *ChannelHealthProbeRunUpsertOne {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.ClearTtftMs()
	})
}

// SetTotalMs sets the "total_ms" field.
func (u *ChannelHealthProbeRunUpsertOne) SetTotalMs(v float64) *ChannelHealthProbeRunUpsertOne {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.SetTotalMs(v)
	})
}

// AddTotalMs adds v to the "total_ms" field.
func (u *ChannelHealthProbeRunUpsertOne) AddTotalMs(v float64) *ChannelHealthProbeRunUpsertOne {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.AddTotalMs(v)
	})
}

// UpdateTotalMs sets the "total_ms" field to the value that was provided on create.
func (u *ChannelHealthProbeRunUpsertOne) UpdateTotalMs() *ChannelHealthProbeRunUpsertOne {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.UpdateTotalMs()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *ChannelHealthProbeRunUpsertOne) SetErrorMessage(v string) *ChannelHealthProbeRunUpsertOne {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *ChannelHealthProbeRunUpsertOne) UpdateErrorMessage() *ChannelHealthProbeRunUpsertOne {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *ChannelHealthProbeRunUpsertOne) ClearErrorMessage() *ChannelHealthProbeRunUpsertOne {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.ClearErrorMessage()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *ChannelHealthProbeRunUpsertOne) SetCompletedAt(v time.Time) *ChannelHealthProbeRunUpsertOne {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *ChannelHealthProbeRunUpsertOne) UpdateCompletedAt() *ChannelHealthProbeRunUpsertOne {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *ChannelHealthProbeRunUpsertOne) ClearCompletedAt() *ChannelHealthProbeRunUpsertOne {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.ClearCompletedAt()
	})
}

// Exec executes the query.
func (u *ChannelHealthProbeRunUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChannelHealthProbeRunCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChannelHealthProbeRunUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChannelHealthProbeRunUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChannelHealthProbeRunUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChannelHealthProbeRunCreateBulk is the builder for creating many ChannelHealthProbeRun entities in bulk.
type ChannelHealthProbeRunCreateBulk struct {
	config
	err      error
	builders []*ChannelHealthProbeRunCreate
	conflict []sql.ConflictOption
}

// Save creates the ChannelHealthProbeRun entities in the database.
func (_c *ChannelHealthProbeRunCreateBulk) Save(ctx context.Context) ([]*ChannelHealthProbeRun, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChannelHealthProbeRun, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChannelHealthProbeRunMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChannelHealthProbeRunCreateBulk) SaveX(ctx context.Context) []*ChannelHealthProbeRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelHealthProbeRunCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelHealthProbeRunCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChannelHealthProbeRun.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChannelHealthProbeRunUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ChannelHealthProbeRunCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChannelHealthProbeRunUpsertBulk {
	_c.conflict = opts
	return &ChannelHealthProbeRunUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChannelHealthProbeRun.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChannelHealthProbeRunCreateBulk) OnConflictColumns(columns ...string) *ChannelHealthProbeRunUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChannelHealthProbeRunUpsertBulk{
		create: _c,
	}
}

// ChannelHealthProbeRunUpsertBulk is the builder for "upsert"-ing
// a bulk of ChannelHealthProbeRun nodes.
type ChannelHealthProbeRunUpsertBulk struct {
	create *ChannelHealthProbeRunCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ChannelHealthProbeRun.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChannelHealthProbeRunUpsertBulk) UpdateNewValues() *ChannelHealthProbeRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(channelhealthproberun.FieldCreatedAt)
			}
			if _, exists := b.mutation.ChannelID(); exists {
				s.SetIgnore(channelhealthproberun.FieldChannelID)
			}
			if _, exists := b.mutation.ModelID(); exists {
				s.SetIgnore(channelhealthproberun.FieldModelID)
			}
			if _, exists := b.mutation.Source(); exists {
				s.SetIgnore(channelhealthproberun.FieldSource)
			}
			if _, exists := b.mutation.Stream(); exists {
				s.SetIgnore(channelhealthproberun.FieldStream)
			}
			if _, exists := b.mutation.ScheduleKey(); exists {
				s.SetIgnore(channelhealthproberun.FieldScheduleKey)
			}
			if _, exists := b.mutation.StartedAt(); exists {
				s.SetIgnore(channelhealthproberun.FieldStartedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChannelHealthProbeRun.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChannelHealthProbeRunUpsertBulk) Ignore() *ChannelHealthProbeRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChannelHealthProbeRunUpsertBulk) DoNothing() *ChannelHealthProbeRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChannelHealthProbeRunCreateBulk.OnConflict
// documentation for more info.
func (u *ChannelHealthProbeRunUpsertBulk) Update(set func(*ChannelHealthProbeRunUpsert)) *ChannelHealthProbeRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChannelHealthProbeRunUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChannelHealthProbeRunUpsertBulk) SetUpdatedAt(v time.Time) *ChannelHealthProbeRunUpsertBulk {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChannelHealthProbeRunUpsertBulk) UpdateUpdatedAt() *ChannelHealthProbeRunUpsertBulk {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetStatus sets the "status" field.
func (u *ChannelHealthProbeRunUpsertBulk) SetStatus(v channelhealthproberun.Status) *ChannelHealthProbeRunUpsertBulk {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChannelHealthProbeRunUpsertBulk) UpdateStatus() *ChannelHealthProbeRunUpsertBulk {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.UpdateStatus()
	})
}

// SetTtfbMs sets the "ttfb_ms" field.
func (u *ChannelHealthProbeRunUpsertBulk) SetTtfbMs(v float64) *ChannelHealthProbeRunUpsertBulk {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.SetTtfbMs(v)
	})
}

// AddTtfbMs adds v to the "ttfb_ms" field.
func (u *ChannelHealthProbeRunUpsertBulk) AddTtfbMs(v float64) *ChannelHealthProbeRunUpsertBulk {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.AddTtfbMs(v)
	})
}

// UpdateTtfbMs sets the "ttfb_ms" field to the value that was provided on create.
func (u *ChannelHealthProbeRunUpsertBulk) UpdateTtfbMs() *ChannelHealthProbeRunUpsertBulk {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.UpdateTtfbMs()
	})
}

// ClearTtfbMs clears the value of the "ttfb_ms" field.
func (u *ChannelHealthProbeRunUpsertBulk) ClearTtfbMs() *ChannelHealthProbeRunUpsertBulk {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.ClearTtfbMs()
	})
}

// SetTtftMs sets the "ttft_ms" field.
func (u *ChannelHealthProbeRunUpsertBulk) SetTtftMs(v float64) *ChannelHealthProbeRunUpsertBulk {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.SetTtftMs(v)
	})
}

// AddTtftMs adds v to the "ttft_ms" field.
func (u *ChannelHealthProbeRunUpsertBulk) AddTtftMs(v float64) *ChannelHealthProbeRunUpsertBulk {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.AddTtftMs(v)
	})
}

// UpdateTtftMs sets the "ttft_ms" field to the value that was provided on create.
func (u *ChannelHealthProbeRunUpsertBulk) UpdateTtftMs() *ChannelHealthProbeRunUpsertBulk {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.UpdateTtftMs()
	})
}

// ClearTtftMs clears the value of the "ttft_ms" field.
func (u *ChannelHealthProbeRunUpsertBulk) ClearTtftMs() *ChannelHealthProbeRunUpsertBulk {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.ClearTtftMs()
	})
}

// SetTotalMs sets the "total_ms" field.
func (u *ChannelHealthProbeRunUpsertBulk) SetTotalMs(v float64) *ChannelHealthProbeRunUpsertBulk {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.SetTotalMs(v)
	})
}

// AddTotalMs adds v to the "total_ms" field.
func (u *ChannelHealthProbeRunUpsertBulk) AddTotalMs(v float64) *ChannelHealthProbeRunUpsertBulk {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.AddTotalMs(v)
	})
}

// UpdateTotalMs sets the "total_ms" field to the value that was provided on create.
func (u *ChannelHealthProbeRunUpsertBulk) UpdateTotalMs() *ChannelHealthProbeRunUpsertBulk {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.UpdateTotalMs()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *ChannelHealthProbeRunUpsertBulk) SetErrorMessage(v string) *ChannelHealthProbeRunUpsertBulk {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *ChannelHealthProbeRunUpsertBulk) UpdateErrorMessage() *ChannelHealthProbeRunUpsertBulk {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *ChannelHealthProbeRunUpsertBulk) ClearErrorMessage() *ChannelHealthProbeRunUpsertBulk {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.ClearErrorMessage()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *ChannelHealthProbeRunUpsertBulk) SetCompletedAt(v time.Time) *ChannelHealthProbeRunUpsertBulk {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *ChannelHealthProbeRunUpsertBulk) UpdateCompletedAt() *ChannelHealthProbeRunUpsertBulk {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *ChannelHealthProbeRunUpsertBulk) ClearCompletedAt() *ChannelHealthProbeRunUpsertBulk {
	return u.Update(func(s *ChannelHealthProbeRunUpsert) {
		s.ClearCompletedAt()
	})
}

// Exec executes the query.
func (u *ChannelHealthProbeRunUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ChannelHealthProbeRunCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChannelHealthProbeRunCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChannelHealthProbeRunUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
