// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/channelhealthproberun"
)

// ChannelHealthProbeRun is the model entity for the ChannelHealthProbeRun schema.
type ChannelHealthProbeRun struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ChannelID holds the value of the "channel_id" field.
	ChannelID int `json:"channel_id,omitempty"`
	// ModelID holds the value of the "model_id" field.
	ModelID string `json:"model_id,omitempty"`
	// Source holds the value of the "source" field.
	Source channelhealthproberun.Source `json:"source,omitempty"`
	// Status holds the value of the "status" field.
	Status channelhealthproberun.Status `json:"status,omitempty"`
	// Stream holds the value of the "stream" field.
	Stream bool `json:"stream,omitempty"`
	// TtfbMs holds the value of the "ttfb_ms" field.
	TtfbMs *float64 `json:"ttfb_ms,omitempty"`
	// TtftMs holds the value of the "ttft_ms" field.
	TtftMs *float64 `json:"ttft_ms,omitempty"`
	// TotalMs holds the value of the "total_ms" field.
	TotalMs float64 `json:"total_ms,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// ScheduleKey holds the value of the "schedule_key" field.
	ScheduleKey *string `json:"schedule_key,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChannelHealthProbeRunQuery when eager-loading is set.
	Edges        ChannelHealthProbeRunEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ChannelHealthProbeRunEdges holds the relations/edges for other nodes in the graph.
type ChannelHealthProbeRunEdges struct {
	// Channel holds the value of the channel edge.
	Channel *Channel `json:"channel,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int
}

// ChannelOrErr returns the Channel value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChannelHealthProbeRunEdges) ChannelOrErr() (*Channel, error) {
	if e.Channel != nil {
		return e.Channel, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: channel.Label}
	}
	return nil, &NotLoadedError{edge: "channel"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChannelHealthProbeRun) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case channelhealthproberun.FieldStream:
			values[i] = new(sql.NullBool)
		case channelhealthproberun.FieldTtfbMs, channelhealthproberun.FieldTtftMs, channelhealthproberun.FieldTotalMs:
			values[i] = new(sql.NullFloat64)
		case channelhealthproberun.FieldID, channelhealthproberun.FieldChannelID:
			values[i] = new(sql.NullInt64)
		case channelhealthproberun.FieldModelID, channelhealthproberun.FieldSource, channelhealthproberun.FieldStatus, channelhealthproberun.FieldErrorMessage, channelhealthproberun.FieldScheduleKey:
			values[i] = new(sql.NullString)
		case channelhealthproberun.FieldCreatedAt, channelhealthproberun.FieldUpdatedAt, channelhealthproberun.FieldStartedAt, channelhealthproberun.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChannelHealthProbeRun fields.
func (_m *ChannelHealthProbeRun) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case channelhealthproberun.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case channelhealthproberun.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case channelhealthproberun.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case channelhealthproberun.FieldChannelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value.Valid {
				_m.ChannelID = int(value.Int64)
			}
		case channelhealthproberun.FieldModelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_id", values[i])
			} else if value.Valid {
				_m.ModelID = value.String
			}
		case channelhealthproberun.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = channelhealthproberun.Source(value.String)
			}
		case channelhealthproberun.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = channelhealthproberun.Status(value.String)
			}
		case channelhealthproberun.FieldStream:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field stream", values[i])
			} else if value.Valid {
				_m.Stream = value.Bool
			}
		case channelhealthproberun.FieldTtfbMs:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field ttfb_ms", values[i])
			} else if value.Valid {
				_m.TtfbMs = new(float64)
				*_m.TtfbMs = value.Float64
			}
		case channelhealthproberun.FieldTtftMs:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field ttft_ms", values[i])
			} else if value.Valid {
				_m.TtftMs = new(float64)
				*_m.TtftMs = value.Float64
			}
		case channelhealthproberun.FieldTotalMs:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_ms", values[i])
			} else if value.Valid {
				_m.TotalMs = value.Float64
			}
		case channelhealthproberun.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case channelhealthproberun.FieldScheduleKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field schedule_key", values[i])
			} else if value.Valid {
				_m.ScheduleKey = new(string)
				*_m.ScheduleKey = value.String
			}
		case channelhealthproberun.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case channelhealthproberun.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChannelHealthProbeRun.
// This includes values selected through modifiers, order, etc.
func (_m *ChannelHealthProbeRun) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChannel queries the "channel" edge of the ChannelHealthProbeRun entity.
func (_m *ChannelHealthProbeRun) QueryChannel() *ChannelQuery {
	return NewChannelHealthProbeRunClient(_m.config).QueryChannel(_m)
}

// Update returns a builder for updating this ChannelHealthProbeRun.
// Note that you need to call ChannelHealthProbeRun.Unwrap() before calling this method if this ChannelHealthProbeRun
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChannelHealthProbeRun) Update() *ChannelHealthProbeRunUpdateOne {
	return NewChannelHealthProbeRunClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChannelHealthProbeRun entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChannelHealthProbeRun) Unwrap() *ChannelHealthProbeRun {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChannelHealthProbeRun is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChannelHealthProbeRun) String() string {
	var builder strings.Builder
	builder.WriteString("ChannelHealthProbeRun(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("channel_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChannelID))
	builder.WriteString(", ")
	builder.WriteString("model_id=")
	builder.WriteString(_m.ModelID)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(fmt.Sprintf("%v", _m.Source))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("stream=")
	builder.WriteString(fmt.Sprintf("%v", _m.Stream))
	builder.WriteString(", ")
	if v := _m.TtfbMs; v != nil {
		builder.WriteString("ttfb_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TtftMs; v != nil {
		builder.WriteString("ttft_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("total_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalMs))
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ScheduleKey; v != nil {
		builder.WriteString("schedule_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ChannelHealthProbeRuns is a parsable slice of ChannelHealthProbeRun.
type ChannelHealthProbeRuns []*ChannelHealthProbeRun
