package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/looplj/axonhub/internal/objects"
	"github.com/looplj/axonhub/internal/server/biz"
)

// SetChannelCallerAccessPolicy is the resolver for the setChannelCallerAccessPolicy field.
func (r *mutationResolver) SetChannelCallerAccessPolicy(ctx context.Context, input biz.SetChannelCallerAccessPolicyInput) (*biz.ChannelCallerAccessPolicy, error) {
	return r.channelService.SetChannelCallerAccessPolicy(ctx, input)
}

// ChannelCallerAccessPolicy is the resolver for the channelCallerAccessPolicy field.
func (r *queryResolver) ChannelCallerAccessPolicy(ctx context.Context, channelID objects.GUID) (*biz.ChannelCallerAccessPolicy, error) {
	return r.channelService.ChannelCallerAccessPolicy(ctx, channelID.ID)
}

// ChannelCallerAccessCandidates is the resolver for the channelCallerAccessCandidates field.
func (r *queryResolver) ChannelCallerAccessCandidates(ctx context.Context) ([]*biz.ChannelCallerAPIKeySummary, error) {
	return r.channelService.ChannelCallerAccessCandidates(ctx)
}

// APIKeyChannelCallerAccess is the resolver for the apiKeyChannelCallerAccess field.
func (r *queryResolver) APIKeyChannelCallerAccess(ctx context.Context, apiKeyID objects.GUID) ([]*biz.APIKeyChannelCallerAccess, error) {
	return r.channelService.APIKeyChannelCallerAccess(ctx, apiKeyID.ID)
}
