package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/looplj/axonhub/internal/objects"
	"github.com/looplj/axonhub/internal/server/biz"
)

// Items is the resolver for the items field.
func (r *channelHealthProbeHistoryPageResolver) Items(ctx context.Context, obj *biz.ChannelHealthProbeHistoryPage) ([]*ActiveChannelHealthProbeRun, error) {
	items := make([]*ActiveChannelHealthProbeRun, 0, len(obj.Items))
	for _, item := range obj.Items {
		items = append(items, activeChannelHealthProbeRun(item))
	}
	return items, nil
}

// LatestRun is the resolver for the latestRun field.
func (r *channelHealthProbeModelOverviewResolver) LatestRun(ctx context.Context, obj *biz.ChannelHealthProbeModelOverview) (*ActiveChannelHealthProbeRun, error) {
	return activeChannelHealthProbeRun(obj.LatestRun), nil
}

// UpdateChannelHealthProbeSettings is the resolver for the updateChannelHealthProbeSettings field.
func (r *mutationResolver) UpdateChannelHealthProbeSettings(ctx context.Context, input biz.UpdateChannelHealthProbeSettingsInput) (*ChannelHealthProbeChannel, error) {
	item, err := r.channelHealthProbeService.UpdateSettings(ctx, input)
	if err != nil {
		return nil, err
	}
	return activeChannelHealthProbeChannel(item), nil
}

// UpdateChannelHealthProbePolicy is the resolver for the updateChannelHealthProbePolicy field.
func (r *mutationResolver) UpdateChannelHealthProbePolicy(ctx context.Context, input biz.UpdateChannelHealthProbePolicyInput) (*biz.ChannelHealthProbePolicy, error) {
	return r.channelHealthProbeService.UpdatePolicy(ctx, input)
}

// RunChannelHealthProbe is the resolver for the runChannelHealthProbe field.
func (r *mutationResolver) RunChannelHealthProbe(ctx context.Context, input biz.RunChannelHealthProbeInput) (*ActiveChannelHealthProbeRun, error) {
	item, err := r.channelHealthProbeRunner.RunManual(ctx, input)
	if err != nil {
		return nil, err
	}
	return activeChannelHealthProbeRun(item), nil
}

// ChannelHealthProbeOverview is the resolver for the channelHealthProbeOverview field.
func (r *queryResolver) ChannelHealthProbeOverview(ctx context.Context) ([]*ChannelHealthProbeChannel, error) {
	items, err := r.channelHealthProbeService.Overview(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*ChannelHealthProbeChannel, 0, len(items))
	for _, item := range items {
		result = append(result, activeChannelHealthProbeChannel(item))
	}
	return result, nil
}

// ChannelHealthProbePolicy is the resolver for the channelHealthProbePolicy field.
func (r *queryResolver) ChannelHealthProbePolicy(ctx context.Context) (*biz.ChannelHealthProbePolicy, error) {
	return r.channelHealthProbeService.Policy(ctx)
}

// ChannelHealthProbeHistory is the resolver for the channelHealthProbeHistory field.
func (r *queryResolver) ChannelHealthProbeHistory(ctx context.Context, input biz.ChannelHealthProbeHistoryInput) (*biz.ChannelHealthProbeHistoryPage, error) {
	return r.channelHealthProbeService.History(ctx, input)
}

// Models is the resolver for the models field.
func (r *updateChannelHealthProbePolicyInputResolver) Models(ctx context.Context, obj *biz.UpdateChannelHealthProbePolicyInput, data []*ActiveHealthProbeModelSettingInput) error {
	panic(fmt.Errorf("not implemented: Models - models"))
}

// Models is the resolver for the models field.
func (r *updateChannelHealthProbeSettingsInputResolver) Models(ctx context.Context, obj *biz.UpdateChannelHealthProbeSettingsInput, data []*ActiveChannelHealthProbeModelInput) error {
	obj.Models = make([]objects.ChannelHealthProbeModel, 0, len(data))
	for _, item := range data {
		if item == nil {
			continue
		}
		obj.Models = append(obj.Models, objects.ChannelHealthProbeModel{
			ModelID: item.ModelID,
			Enabled: item.Enabled,
			Stream:  item.Stream,
		})
	}
	return nil
}

// ChannelHealthProbeHistoryPage returns ChannelHealthProbeHistoryPageResolver implementation.
func (r *Resolver) ChannelHealthProbeHistoryPage() ChannelHealthProbeHistoryPageResolver {
	return &channelHealthProbeHistoryPageResolver{r}
}

// ChannelHealthProbeModelOverview returns ChannelHealthProbeModelOverviewResolver implementation.
func (r *Resolver) ChannelHealthProbeModelOverview() ChannelHealthProbeModelOverviewResolver {
	return &channelHealthProbeModelOverviewResolver{r}
}

// UpdateChannelHealthProbePolicyInput returns UpdateChannelHealthProbePolicyInputResolver implementation.
func (r *Resolver) UpdateChannelHealthProbePolicyInput() UpdateChannelHealthProbePolicyInputResolver {
	return &updateChannelHealthProbePolicyInputResolver{r}
}

// UpdateChannelHealthProbeSettingsInput returns UpdateChannelHealthProbeSettingsInputResolver implementation.
func (r *Resolver) UpdateChannelHealthProbeSettingsInput() UpdateChannelHealthProbeSettingsInputResolver {
	return &updateChannelHealthProbeSettingsInputResolver{r}
}

type channelHealthProbeHistoryPageResolver struct{ *Resolver }
type channelHealthProbeModelOverviewResolver struct{ *Resolver }
type updateChannelHealthProbePolicyInputResolver struct{ *Resolver }
type updateChannelHealthProbeSettingsInputResolver struct{ *Resolver }
